# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 02:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_file', models.FileField(upload_to='note/')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OldQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_question_file', models.FileField(upload_to='old_question/')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2066), django.core.validators.MaxValueValidator(2018)])),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_number', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2066), django.core.validators.MaxValueValidator(2018)])),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_file', models.FileField(upload_to='solution/')),
                ('subject', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(2066), django.core.validators.MaxValueValidator(2018)])),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_file', models.FileField(upload_to='syllabus/')),
                ('subject', models.CharField(max_length=100)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Semester')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Semester'),
        ),
        migrations.AddField(
            model_name='oldquestion',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Semester'),
        ),
        migrations.AddField(
            model_name='note',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Semester'),
        ),
    ]
