# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldquestion',
            name='subject',
            field=models.CharField(max_length=1000),
        ),
    ]
