# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0002_auto_20181120_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldquestion',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: 2066'),
        ),
    ]
