# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0003_auto_20181210_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Use the following format: 2066')),
            ],
        ),
        migrations.AlterField(
            model_name='oldquestion',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Year'),
        ),
        migrations.AlterField(
            model_name='result',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Year'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theory.Year'),
        ),
    ]
