# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='answer_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('question_body', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='question')),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('number_of_ans', models.IntegerField()),
                ('number_of_views', models.IntegerField()),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
