# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0002_delete_answer_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_reply_at', models.DateTimeField()),
                ('answer_reply_body', models.CharField(max_length=100)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Questions')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_at', models.DateTimeField()),
                ('answer_body', models.CharField(max_length=100)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussion.Questions')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
