# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_answer_reply_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_body',
            field=models.CharField(max_length=1000),
        ),
    ]
