# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
