# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0003_auto_20181113_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='re_password',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
