# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-06 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_auto_20181123_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='re_password',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
